name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js (use the desired version, here we use v16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # Run tests (replace with your actual test command if different)
      - name: Run Tests
        run: npx playwright test

