name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        npm install
        npx playwright install  # Ensure all necessary browser binaries are installed

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff2dec1 \
          libvpx6 \
          libevent-2.1-7 \
          libopus0 \
          libgstreamer-plugins-base1.0-0 \
          libgstreamer1.0-0 \
          libflite1 \
          libx264-152 \
          libgles2 \
          libharfbuzz0b

    - name: Run Playwright tests
      run: npx playwright test
